param:
  data_dir :  "./data/processed/waveform/train/SNUH/*.npy"
  learning_win : 60
  pred_win : 60
  sampling_rate : 100
  init_lr: 5.0e-5 #1.0e-5 #5.0e-5 # 2.0e-5, 5.0e-5
  num_epochs: 20
  demo_shape: 0 # no 적용
  batch_size: 512
  n_cv_split : 0


